server {
    server_name ecom.neuro-mind.net;

    client_max_body_size 100M;
    
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/ecom.neuro-mind.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ecom.neuro-mind.net/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location /static/ {
        alias /home/administrator/simulate_ecom/static/;
    }

    location /media/ {
        alias /home/administrator/simulate_ecom/media/;
    }

    location / {
        include proxy_params;
        proxy_intercept_errors on;
        proxy_pass http://localhost:8001;
    }
}

server {
    if ($host = ecom.neuro-mind.net) {
        return 301 https://$host$request_uri;
    }
    # listen 80;
    server_name ecom.neuro-mind.net;
    return 404;
}
